bsr <- read.csv("bsrus.tsv",sep="\t",header=TRUE,quote="",encoding="UTF-8")
bsg <- read.csv("bsger.tsv",sep="\t",header=TRUE,quote="",encoding="UTF-8")
par(mfrow=c(1,4))
boxplot(bsr$entropy)
abline(h=0.143, col = "Red", lty = 5, lwd =3)
title(xlab="Russian", ylab="Difference in entropy")
boxplot(bsr$bwo)
abline(h=0.030, col = "Red", lty = 5, lwd =3)
title(xlab="Russian", ylab="Difference in proportion of basic WO")
boxplot(bsg$entropy, ylim = c(-0.05,0.05))
abline(h=0.049, col = "Red", lty = 5, lwd =3)
title(xlab="German", ylab="Difference in entropy")
boxplot(bsg$bwo, ylim = c(-0.035,0.035))
abline(h=0.032, col = "Red", lty = 5, lwd =3)
title(xlab="German", ylab="Difference in proportion of basic WO")
